version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - 3000:3000
    command: npm run dev
